version: 2
updates:
  # Dependencies for the API
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"

  # Dependencies for the App
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
