name: Production
on:
  push:
    branches:
      - "main"

jobs:
  dockerize:
    name: production-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.REGISTERY_ACCESS_TOKEN }}
      - name: Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Build the image
        run: |
          cd build
          doctl registry login
          docker build -t api .
          docker tag api:latest registry.digitalocean.com/tinyblog/api:latest
          docker push registry.digitalocean.com/tinyblog/api:latest
          doctl registry garbage-collection start tinyblog --force
